### ISSUE TITLE
Problems with include files in 2.0.0

### ISSUE THREAD

**Issue by gcode-importer** [uclouvain/openjpeg#207]
Originally reported on Google Code with ID 207

```
While getting poppler to work with openjpeg 2.0.0 I have been getting some compiler
error and warnings.

In file included from /usr/local/include/openjpeg-2.0/openjpeg.h:92:0,
                 from JPEG2000Stream2.h:18,
                 from JPEG2000Stream2.cc:15:
/usr/local/include/openjpeg-2.0/opj_stdint.h:46:9: error: 'size_t' does not name a
type
In file included from JPEG2000Stream2.h:18:0,
                 from JPEG2000Stream2.cc:15:
/usr/local/include/openjpeg-2.0/openjpeg.h:479:20: error: ISO C++ forbids declaration
of 'OPJ_SIZE_T' with no type [-fpermissive]
/usr/local/include/openjpeg-2.0/openjpeg.h:479:20: error: typedef 'OPJ_SIZE_T' is initialized
(use decltype instead)
/usr/local/include/openjpeg-2.0/openjpeg.h:479:23: error: 'opj_stream_read_fn' was
not declared in this scope
/usr/local/include/openjpeg-2.0/openjpeg.h:484:20: error: ISO C++ forbids declaration
of 'OPJ_SIZE_T' with no type [-fpermissive]
/usr/local/include/openjpeg-2.0/openjpeg.h:484:20: error: typedef 'OPJ_SIZE_T' is initialized
(use decltype instead)
/usr/local/include/openjpeg-2.0/openjpeg.h:484:23: error: 'opj_stream_write_fn' was
not declared in this scope
/usr/local/include/openjpeg-2.0/openjpeg.h:993:54: error: 'OPJ_SIZE_T' was not declared
in this scope
/usr/local/include/openjpeg-2.0/openjpeg.h:993:89: error: expected primary-expression
before 'p_is_input'
/usr/local/include/openjpeg-2.0/openjpeg.h:993:99: error: expression list treated as
compound expression in initializer [-fpermissive]
/usr/local/include/openjpeg-2.0/openjpeg.h:1008:80: error: 'opj_stream_read_fn' has
not been declared
/usr/local/include/openjpeg-2.0/openjpeg.h:1015:81: error: 'opj_stream_write_fn' has
not been declared
/usr/local/include/openjpeg-2.0/openjpeg.h:1052:75: error: 'FILE' was not declared
in this scope
/usr/local/include/openjpeg-2.0/openjpeg.h:1052:82: error: 'p_file' was not declared
in this scope
/usr/local/include/openjpeg-2.0/openjpeg.h:1052:99: error: expected primary-expression
before 'p_is_read_stream'
/usr/local/include/openjpeg-2.0/openjpeg.h:1052:115: error: expression list treated
as compound expression in initializer [-fpermissive]
/usr/local/include/openjpeg-2.0/openjpeg.h:1060:67: error: 'FILE' was not declared
in this scope
/usr/local/include/openjpeg-2.0/openjpeg.h:1060:74: error: 'p_file' was not declared
in this scope
/usr/local/include/openjpeg-2.0/openjpeg.h:1060:82: error: 'OPJ_SIZE_T' was not declared
in this scope
/usr/local/include/openjpeg-2.0/openjpeg.h:1060:117: error: expected primary-expression
before 'p_is_read_stream'
/usr/local/include/openjpeg-2.0/openjpeg.h:1060:133: error: expression list treated
as compound expression in initializer [-fpermissive]


The problem is openjpeg.h is using types like size_t and FILE* without including the
appropriate header files. I can fix the problem by putting a #include <stdio.h> before
the #include <openjpeg.h> but I should not have to do this.

I've also been getting this warning:

/usr/local/include/openjpeg-2.0/opj_config.h:22:0: warning: "HAVE_FSEEKO" redefined

because config.h in poppler has already defined HAVE_FSEEKO. I'm not sure why openjpeg
is polluting public header files with commonly used #defines. I could not see where
HAVE_FSEEKO is used in any of the openjpeg public header files.

I have not tried building with windows however I expect the stdint types defined in
opj_stdint.h will cause problems with duplicate type definitions since poppler and
other projects have also created the stdint types on windows. 

The openjpeg header files should ensure that all public symbols and macros are prefixed
with opj to avoid name space collisions.

```

Reported by `adrian.johnson` on 2013-01-01 14:22:59
